apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mygolang
  name: mygolang
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mygolang
  strategy: {}
  template:
    metadata:
      labels:
        app: mygolang
    spec:
      containers:
      - image: {{ .Values.image }}
        name: comment
        resources: {}
        ports:
          - containerPort: 80
status: {}
